### ISSUE TITLE
Dataset Refresh Delay Issue

### ISSUE THREAD

**Issue by AliOsm** [ARBML/masader-webservice#1]
Currently, I'm loading the dataset in-memory from HF datasets once app starts. Then, for each request to `/datasets` endpoint and based on a random value, I decide to force a fresh dataset download. The random value should be <= 0.1 to initiate the fresh dataset download ([ref](https://github.com/ARBML/masader-webservice/blob/cc50348e5dc20a7f14f797f09330e57a1f00433c/app.py#L21)).

The dataset should be in-memory to response quickly to requests.

I'm not sure, but this could make a delay problem in future as the dataset will not get updated instantly after publishing new version on HF. The delay is not huge as the fresh dataset download happens every ~10 requests to the `/datasets` endpoint. If we wanted to refresh the dataset instantly, we can restart the server from Heroku (If it is very urgent).

I'm mentioning this here just to be aware and for future maintainers :)

**Comment by yousef337** [comment]
The current solution seems satisfiable, however, I think it is possible to reload only when the dataset have changed by comparing its hash value. This approach will ensure that refresh is only done if a change have occured
