### ISSUE TITLE
Multiple Workers With Different In-Memory Data

### ISSUE THREAD

**Issue by AliOsm** [ARBML/masader-webservice#10]
We were using just 1 worker to handle requests on the service, now I scaled this to 2 workers, but I realized that each of them will have different data in-memory because the `/refresh` requests will be handled by one of the workers each time.

To solve this issue, instead of storing the data in-memory, we should retrieve it each time from Redis. The data already in Redis with `masader` and `tags` keys. We just need to retrieve it and return the required data from the ednpoints.

**Comment by AliOsm** [comment]
BTW, this will create very funny situation. Two users can open the website in the same time and retrieve different datasets if the two workers are not synced :3

**Comment by zaidalyafeai** [comment]
We dont have that much traffic.

**Comment by AliOsm** [comment]
I fixed this, resolving...
