### ISSUE TITLE
Last dataset is always missing 

### ISSUE THREAD

**Issue by zaidalyafeai** [ARBML/masader-webservice#13]
The sheet has now 591 datasets but it seems the api call: https://masader-web-service.herokuapp.com/datasets?features=Name only retrieves 590.

**Comment by AliOsm** [comment]
I will look into this

**Comment by AliOsm** [comment]
There is no issue in the endpoint, the problem happens in HF dataset. Try this:

```
from datasets import Dataset, DownloadMode, load_dataset

masader = load_dataset(
    'arbml/masader',
    download_mode=DownloadMode.FORCE_REDOWNLOAD,
    ignore_verifications=True,
)['train']

print(len(masader)) # -> 590
```

It outputs `590`.

**Comment by zaidalyafeai** [comment]
fixed, ty.

**Comment by zaidalyafeai** [comment]
The problem presists even though it is fixed on hf. Are we refreshing the datasets correctly?

**Comment by AliOsm** [comment]
Resolved, the issue was a wrong value in Redis related to the last dataset that calculated when HF API was down.
