### ISSUE TITLE
Can't access url content from external machines

### ISSUE THREAD

**Issue by sudomaze** [ARBML/masader-webservice#5]
While working on pulling the data for this issue (https://github.com/ARBML/masader/issues/19), I was getting the following error:

```
Access to XMLHttpRequest at 'https://masader-web-service.herokuapp.com/datasets' from origin 
'http://127.0.0.1:4000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header 
is present on the requested resource.
```

Which indicates that the server doesn't accept external requests. I am working on a solution under my fork and I will test it on heroku servers.

**Comment by AliOsm** [comment]
I can disable CORS from the server side by the EOD. For now, you can install any browser extension that disables CORS.

**Comment by sudomaze** [comment]
Sure, if that is an easy thing to do. Could you please do that so I can test your link?

**Comment by AliOsm** [comment]
Could you please try it now? I just allowed CORS for all endpoints.

**Comment by sudomaze** [comment]
It works! I will push the changes and close this issue. Thanks!
