### ISSUE TITLE
Multiple Datasets With Similar Embeddings

### ISSUE THREAD

**Issue by AliOsm** [ARBML/masader-webservice#6]
Currently, we are using Abstract, Tasks, and Description to calculate the dataset embeddings. Some datasets have the same values for these three features. Based on this fact, their embeddings will be similar, and accordingly, their positions on the explore graph will be the same.

The datasets that have this issue can be found here: http://jsonblob.com/992172744531787776.

Suggested solutions:
- Add other features to the embeddings prompt.
- Anything else?

**Comment by zaidalyafeai** [comment]
Dataset names should work as extra feature.

**Comment by AliOsm** [comment]
Should we implement this?

**Comment by zaidalyafeai** [comment]
Not high priority.

**Comment by zaidalyafeai** [comment]
I will test this offline.

**Comment by zaidalyafeai** [comment]
resolved in https://github.com/ARBML/masader-webservice/pull/18
